//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TanglAnalyzer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TanglAnalyzer.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type names should be all uppercase..
        /// </summary>
        internal static string AnalyzerDescription {
            get {
                return ResourceManager.GetString("AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type name &apos;{0}&apos; contains lowercase letters.
        /// </summary>
        internal static string AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type name contains lowercase letters.
        /// </summary>
        internal static string AnalyzerTitle {
            get {
                return ResourceManager.GetString("AnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Differing attribute.
        /// </summary>
        internal static string DifferingAttributeDescription {
            get {
                return ResourceManager.GetString("DifferingAttributeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Differing attribute &apos;{0}&apos;.
        /// </summary>
        internal static string DifferingAttributeMessageFormat {
            get {
                return ResourceManager.GetString("DifferingAttributeMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Differing attribute.
        /// </summary>
        internal static string DifferingAttributeTitle {
            get {
                return ResourceManager.GetString("DifferingAttributeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tangl and Tangl target have differing types..
        /// </summary>
        internal static string DifferingTypesDescription {
            get {
                return ResourceManager.GetString("DifferingTypesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tangle &apos;{0}&apos; and Tangl target &apos;{1}&apos; have differing types..
        /// </summary>
        internal static string DifferingTypesMessageFormat {
            get {
                return ResourceManager.GetString("DifferingTypesMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Differing Tangl and Tangl target types.
        /// </summary>
        internal static string DifferingTypesTitle {
            get {
                return ResourceManager.GetString("DifferingTypesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing attribute .
        /// </summary>
        internal static string MissingAttributeDescription {
            get {
                return ResourceManager.GetString("MissingAttributeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing attribute &apos;{0}&apos;.
        /// </summary>
        internal static string MissingAttributeMessageFormat {
            get {
                return ResourceManager.GetString("MissingAttributeMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing attribute.
        /// </summary>
        internal static string MissingAttributeTitle {
            get {
                return ResourceManager.GetString("MissingAttributeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find Tangl target..
        /// </summary>
        internal static string MissingTargetDescription {
            get {
                return ResourceManager.GetString("MissingTargetDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find Tangl target &apos;{0}&apos;..
        /// </summary>
        internal static string MissingTargetMessageFormat {
            get {
                return ResourceManager.GetString("MissingTargetMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Tangl target..
        /// </summary>
        internal static string MissingTargetTitle {
            get {
                return ResourceManager.GetString("MissingTargetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find type specified in Tangl attribute..
        /// </summary>
        internal static string MissingTargetTypeDescription {
            get {
                return ResourceManager.GetString("MissingTargetTypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type name &apos;{0}&apos; not found..
        /// </summary>
        internal static string MissingTargetTypeMessageFormat {
            get {
                return ResourceManager.GetString("MissingTargetTypeMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing target type.
        /// </summary>
        internal static string MissingTargetTypeTitle {
            get {
                return ResourceManager.GetString("MissingTargetTypeTitle", resourceCulture);
            }
        }
    }
}
